### ISSUE TITLE
Chapter04/importing-pkl-files/07-deserialize-plots-df-into-python-visual.py

### ISSUE THREAD

**Issue by Mikma03** [PacktPublishing/Extending-Power-BI-with-Python-and-R#1]
Hi,

The file under the following path seems to not work... please check.

https://github.com/PacktPublishing/Extending-Power-BI-with-Python-and-R/blob/main/Chapter04/importing-pkl-files/07-deserialize-plots-df-into-python-visual.py

After running the Python script in my Power BI I still receive the following error:

`Error Message:
Þŷτђóπ ѕĉѓїрτ єŕѓòґ.
**ValueError: byte must be in range(0, 256)**

Stack Trace:
Microsoft.PowerBI.ExploreServiceCommon.ScriptHandlerException: Þŷτђóπ ѕĉѓїрτ єŕѓòґ.
ValueError: byte must be in range(0, 256)
 ---> Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException: Þŷτђóπ ѕĉѓїрτ єŕѓòґ.
ValueError: byte must be in range(0, 256)`

**Comment by LeeChang-Soo** [comment]
Hi,

Also, I had the same error .

Please. Check

Thanks

**Comment by lucazav** [comment]
Hi all,

currently I'm in vacation. I'll check the issues as soon as I'll back.

Thank you for your feedback.

**Comment by lucazav** [comment]
@Mikma03 could you share with us the Python and package versions you are using, please?

**Comment by Mikma03** [comment]
Hi,
Sure.

My default Python:


    PS C:\Windows\System32> python --version
    Python 3.10.0

And packages:

- pandas

      In [1]: import pandas as pd
      
      In [2]: print(pd.__version__)
      1.3.5

- pickle

      In [7]: import pickle
      
      In [8]: print(pickle.format_version)
      4.0

- matplotlib

        In [10]: pip show matplotlib
  
        Name: matplotlib
        Version: 3.5.0

**Comment by lucazav** [comment]
Hi @Mikma03,

I used a conda environment with Python 3.9.5, Pandas 1.3.0, Matplotlib 3.4.3. No need to install Pickle, as it is provided in Python by default. All worked for me.
